language: ruby
sudo: false
cache: bundler
rvm:
 - "2.3.1"
addons:
  postgresql: 9.4
services:
  - postgresql
before_script: psql -c 'create database dummy_test;' -U postgres
script:
  - bundle exec rails db:create db:migrate
  - bundle exec rake
